#ifndef _WEB_STRINGS_H_
#define _WEB_STRINGS_H_
const char index_html[] PROGMEM = "<html lang='en'><head>"
"<meta name='format-detection' content='telephone=no'>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>"
"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' integrity='sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm' crossorigin='anonymous'>"
"<script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>"
"<script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'></script>"
"<script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' integrity='sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl' crossorigin='anonymous'></script>"
"<link rel='preconnect' href='https://fonts.googleapis.com'>"
"<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>"
"<link href='https://fonts.googleapis.com/css2?family=MuseoModerno:wght@500&display=swap' rel='stylesheet'>"
"<title>HODLcube Settings</title>"
"<script>function submitMessage() {"
"alert('Values saved.');"
"setTimeout(function() {"
"document.location.reload(false);"
"}, 500);}</script>"
"</head>"
"<body><header class='flex-column flex-md-row navbar' style='background-color: #4d4d4e;color: #ffffff;'>"
"<span style=\"font-family: 'MuseoModerno', cursive;\">HODLcube Settings</span></header>"
"<div class='container'>"
"<h4>Price change thresholds"
"<a class='font-weight-bold' data-toggle='collapse' href='#collapseThresholds' aria-expanded='false' aria-controls='collapseThresholds'> ?</a></h4>"
"<div class='collapse' id='collapseThresholds'>"
"<div class='mb-2 col-sm-4 alert alert-info'>Thresholds affect sesitivity of LEDs and buzzer to price change. Price change means difference between two "
"displayed prices in a row in case of ticker or difference between checkpoint value and current price in case of long term watcher. The lower the screen "
"change delay is, the smaller  the price difference will be and the lower threshold value (higher sensitivity) "
"is needed to activate LEDs or buzzer.</div></div>"
"<form action='/get' target='hidden-form'>"
"<h5>Price ticker</h5>"
"<div class='row mb-2'>"
"<label for='inputLEDtickThresh' class='col-sm-2 col-form-label'>LEDs (percent)"
"<a class='font-weight-bold' data-toggle='collapse' href='#collapseHelpLED' aria-expanded='false' aria-controls='collapseHelpLED'> ?</a></label>"
"<div class='mb-2 col-sm-2'>"
"<input type='number' name='inputLEDtickThresh' step='0.01' min='0' max='100' value='%inputLEDtickThresh%' class='form-control'></div></div>"
"<div class='collapse' id='collapseHelpLED'>"
"<div class='mb-2 col-sm-4 alert alert-info'>This value has to be between 0 (highest price change sensitivity) and 100 (turned off).<br>"
"Example: current price 1.000, threshold 0.01; 1000*(0.01/100)=0.1. LED flashes when price decreases (red) or increases (green) by 0.1.</div></div>"
"<div class='row mb-2'>"
"<label for='inputBuzzTickThresh' class='col-sm-2 col-form-label'>Buzzer (percent)"
"<a class='font-weight-bold' data-toggle='collapse' href='#collapseHelpBuzzTickThresh' aria-expanded='false' aria-controls='collapseHelpBuzzTickThresh'> ?</a></label>"
"<div class='col-sm-2 mb-2'>"
"<input type='number' name='inputBuzzTickThresh' step='0.01' min='0' max='100' value='%inputBuzzTickThresh%' class='form-control'></div></div>"
"<div class='collapse' id='collapseHelpBuzzTickThresh'>"
"<div class='mb-2 col-sm-4 alert alert-info'>This value has to be between 0 (highest price change sensitivity) and 100 (turned off).<br>"
"Example: current price 45.000, threshold 0.5; 45.000*(0.5/100)=225. Buzzer sounds when price changes by 225.</div></div>"
"<h5>Long term price watcher</h5>"
"<div class='row mb-2'>"
"<label for='inputBuzzCPThresh' class='col-sm-2 col-form-label'>Buzzer (percent)"
"<a class='font-weight-bold' data-toggle='collapse' href='#collapseHelpBuzzCPThresh' aria-expanded='false' aria-controls='collapseHelpBuzzCPThresh'> ?</a></label>"
"<div class='col-sm-2 mb-2'>"
"<input type='number' name='inputBuzzCPThresh' step='0.1' min='0.1' value='%inputBuzzCPThresh%' class='form-control'></div></div>"
"<div class='collapse' id='collapseHelpBuzzCPThresh'>"
"<div class='mb-2 col-sm-4 alert alert-info'>This value has to be higher or equal to 0. Buzzer is activated when checkpoint value and current price differs  "
"by specified number of percent. Checkpoint value is created on device startup from the firt displayed price. When the threshold value is reached, the new "
"checkpoint is created.<br>Example: checkpoint 50.000, threshold 5; 50.000*(5/100)=2500. Buzzer sounds when price reaches 52.500 and new checkpoint "
"with the new value is created.</div></div>"
"<div class='row mb-2'>"
"<div class='mb-2 col-sm-4 alert alert-info'>The higher the threshold values are, the less often the LEDs (buzzer) are activated.</div></div>"
"<h4>Currency pairs</h4>"
"<div class='form-check'>"
"<input type='checkbox' name='crypto0' value='btc-usd' %btc-usd% class='form-check-input'>"
"<label for='crypto0' class='form-check-label'>Bitcoin - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto1' value='btc-eur' %btc-eur% class='form-check-input'>"
"<label for='crypto1' class='form-check-label'>Bitcoin - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto2' value='eth-btc' %eth-btc% class='form-check-input'>"
"<label for='crypto2' class='form-check-label'>Bitcoin - Ethereum</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto3' value='eth-usd' %eth-usd% class='form-check-input'>"
"<label for='crypto3' class='form-check-label'>Ethereum - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto4' value='eth-eur' %eth-eur% class='form-check-input'>"
"<label for='crypto4' class='form-check-label'>Ethereum - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto5' value='ltc-usd' %ltc-usd% class='form-check-input'>"
"<label for='crypto5' class='form-check-label'>Litecoin - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto6' value='ltc-eur' %ltc-eur% class='form-check-input'>"
"<label for='crypto7' class='form-check-label'>Litecoin - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto7' value='ltc-btc' %ltc-btc% class='form-check-input'>"
"<label for='crypto8' class='form-check-label'>Litecoin - Bitcoin</label>"
"</div><div class='row mb-2'>"
"<label for='inputScreenChangeDelay' class='col-sm-2 col-form-label'>Screen change delay</label>"
"<div class='col-sm-2 mb-2'><select name='inputScreenChangeDelay' class='form-control'>"
"<option value='2000' %screenChangeDelay2000%>2s</option>"
"<option value='5000' %screenChangeDelay5000%>5s</option>"
"<option value='10000' %screenChangeDelay10000%>10s</option>"
"<option value='15000' %screenChangeDelay15000%>15s</option></select></div></div>"
"<button type='submit' onclick='submitMessage()' class='btn btn-primary mb-2'>Save</button></form>"
"<iframe style='display:none' name='hidden-form'></iframe></div></body></html>";

#endif
