#ifndef _WEB_STRINGS_H_
#define _WEB_STRINGS_H_
const char index_html[] PROGMEM = "<html lang='en'><head>"
"<meta name='format-detection' content='telephone=no'>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>"
"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' integrity='sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm' crossorigin='anonymous'>"
"<link rel='preconnect' href='https://fonts.gstatic.com'>"
"<link href='https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@1,700&amp;display=swap' rel='stylesheet'>"
"<title>HODLcube Settings</title>"
"<script>function submitMessage() {"
"alert('Values saved.');"
"setTimeout(function() {"
"document.location.reload(false);"
"}, 500);}</script>"
"</head>"
"<body><header class='flex-column flex-md-row navbar' style='background-color: #4d4d4e;color: #ffffff;'>"
"<span style=\"font-family: 'Ubuntu', sans-serif;\">#HODLcube Settings</span></header>"
"<div class='container'>"
"<h5>Price change thresholds</h5>"
"<form action='/get' target='hidden-form'>"
"<div class='row mb-2'>"
"<label for='inputLEDthreshold' class='col-sm-2 col-form-label'>LEDs (percent)</label>"
"<div class='mb-2 col-sm-2'>"
"<input type='number' name='inputLEDthreshold' step='0.01' min='0' value='%inputLEDthreshold%' class='form-control'></div></div>"
"<div class='row mb-2'>"
"<label for='inputBuzzerThreshold' class='col-sm-2 col-form-label'>Buzzer (percent)</label>"
"<div class='col-sm-2 mb-2'>"
"<input type='number' name='inputBuzzerThreshold' step='0.01' min='0' value='%inputBuzzerThreshold%' class='form-control'></div></div>"
"<h5>Crypto</h5>"
"<div class='form-check'>"
"<input type='checkbox' name='crypto0' value='btc-usd' %btc-usd% class='form-check-input'>"
"<label for='crypto0' class='form-check-label'>Bitcoin - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto1' value='btc-eur' %btc-eur% class='form-check-input'>"
"<label for='crypto1' class='form-check-label'>Bitcoin - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto2' value='eth-btc' %eth-btc% class='form-check-input'>"
"<label for='crypto2' class='form-check-label'>Bitcoin - Ethereum</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto3' value='eth-usd' %eth-usd% class='form-check-input'>"
"<label for='crypto3' class='form-check-label'>Ethereum - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto4' value='eth-eur' %eth-eur% class='form-check-input'>"
"<label for='crypto4' class='form-check-label'>Ethereum - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto5' value='ltc-usd' %ltc-usd% class='form-check-input'>"
"<label for='crypto5' class='form-check-label'>Litecoin - Dollar</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto6' value='ltc-eur' %ltc-eur% class='form-check-input'>"
"<label for='crypto7' class='form-check-label'>Litecoin - Euro</label>"
"</div><div class='form-check'>"
"<input type='checkbox' name='crypto7' value='ltc-btc' %ltc-btc% class='form-check-input'>"
"<label for='crypto8' class='form-check-label'>Litecoin - Bitcoin</label>"
"</div><div class='row mb-2'>"
"<label for='inputScreenChangeDelay' class='col-sm-2 col-form-label'>Screen change delay</label>"
"<div class='col-sm-2 mb-2'><select name='inputScreenChangeDelay' class='form-control'>"
"<option value='2000' %screenChangeDelay2000%>2s</option>"
"<option value='5000' %screenChangeDelay5000%>5s</option>"
"<option value='10000' %screenChangeDelay10000%>10s</option>"
"<option value='15000' %screenChangeDelay15000%>15s</option></select></div></div>"
"<button type='submit' onclick='submitMessage()' class='btn btn-primary mb-2'>Save</button></form>"
"<iframe style='display:none' name='hidden-form'></iframe></div></body></html>";

#endif
